# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10441977610a28d3bee699ab1fd120ecc1e02a9251bf11b8a4620a05b3db94697144746aa6fa0d88e08a2a540f7bfe717b958bcf1a0442435958f6a9dbcc6d33

test:
  secret_key_base: 521b7c44d455de61b7f23f1f132065a8d438ed5b101c05331f3b30eb09b0876a4889ce67e4bed2784fc2daf719fa6bab09beac215ab273805457623c9531b11a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
